- name: Installation of required packages   #name of the task
  apt:                                      #apt module
    name: "{{ item }}"                      #name of the packages to be installed, item variable will iterate through the loop
    state: present                          #ensures packages are present
  loop:                                     #specifies list of packages
    - python3
    - python3-pip

- name: Install Flask for app1 and app2     #name of the task
  pip:                                      #pip module for managing python packages
    name: Flask                             #python package flask to be installed
    executable: pip3                        #specifying pip3 executable to use

- name: Configure systemd for app1          #task name
  template:                                 #template module
    src: templates/app1.service.j2          #specifies the source template file that contains the systemd service unit configuration for app1
    dest: /etc/systemd/system/app1.service  #dest where template file will be copied
  notify: Restart services

- name: Configure systemd for app2          #task name
  template:                                 #module name
    src: templates/app2.service.j2          #specifies the source template file that contains the systemd service unit configuration for app2
    dest: /etc/systemd/system/app2.service  #dest where template file will be copied
  notify: Restart services
