Vagrant.configure("2") do |config|   #specifying the version of the vagrant
    config.vm.box = "ubuntu/trusty64" #specified the required vbox
    #config.vm.network "forwarded_port", guest: 80, host: 8080 #port forwarding; this allows user to access 
    #services running on port 80 in the VM from the host machine on port 8080
  
    config.vm.define "load_balancer" do |lb| # defined a VM named Load Balancer
      lb.vm.network "private_network", ip: "192.168.33.10" #Configuring a private network for the load balancer VM with DHCP
    end
  
    config.vm.define "application" do |app| #defined a VM named application
      app.vm.network "private_network", ip: "192.168.33.11"
    end
  
      config.vm.define "database" do |db|  #defined a VM named database
      db.vm.network "private_network",  ip: "192.168.33.12"  #Configuring a private network for the load balancer VM with DHCP
    end
      
      config.vm.provision "ansible" do |ansible|    # Specifying provisioner for database
        ansible.playbook = "ansible/playbooks/playbook.yml" #Path to associated playbook
    end
  end